export const MyCV = {
  name: "Wassim Darwish",
  personal_info: {
    date_of_birth: "1989-07-10",
    nationality: "Syrian",
    passport: "N014581360",
    work_permit: "Syrian",
    location: "Al-Sweida, Syria",
    phone: "+963997048181",
    email: "wassimdarwish89@gmail.com",
  },
  summary:
    "Full-stack developer specializing in React, Node.js, and Web3, with a passion for building scalable, user-friendly applications. Experienced in delivering end-to-end solutions across frontend, backend, and blockchain integrations. Highly motivated, adaptable, and committed to continuous learning while driving innovation in fast-paced environments.",
  education: [
    {
      degree: "Bachelors of Information Technology",
      institution: "Syrian Virtual University",
      location: "Damascus, Syria",
      start_date: "2018-06-01",
      end_date: "2020-12-01",
      website: "https://www.svuonline.org",
    },
    {
      degree: "Title of Qualification Awarded",
      institution: "Telecommunication Institute",
      location: "Damascus, Syria",
      start_date: "2007-04-01",
      end_date: "2009-10-01",
    },
  ],
  work_experience: [
    {
      company: "Wellirs",
      position: "Frontend Team Lead / Senior Frontend Developer",
      location: "Al-Shareqa, United Arab Emirates",
      start_date: "2023-02-01",
      end_date: "Present",
      responsibilities: [
        "Defined and documented website specifications including product features, workflows, and technical requirements.",
        "Designed site maps, application models, templates, and UI structures aligned with UX standards.",
        "Developed responsive, high-performance user interfaces using React.",
        "Built and maintained design systems and reusable component libraries.",
        "Implemented authentication, authorization, and security best practices.",
        "Collaborated with product managers, designers, and stakeholders to deliver scalable solutions.",
        "Led the frontend team by assigning tasks, reviewing code, and mentoring developers.",
        "Coordinated cross-functional efforts with backend teams for seamless API integration.",
        "Championed performance optimization and UI/UX consistency across apps.",
        "Facilitated Agile ceremonies and ensured timely project delivery.",
      ],
    },
    {
      company: "Kaskade Finance",
      position: "Fullstack Developer",
      location: "Dubai, United Arab Emirates",
      start_date: "2022-06-01",
      end_date: "2023-01-01",
      responsibilities: [
        "Built and optimized responsive UIs for a cross-chain incentivization platform using React.js.",
        "Developed scalable APIs and Discord bots using Node.js and NestJS.",
        "Implemented database schemas and real-time syncing with Supabase and PostgreSQL.",
        "Automated community engagement features and platform notifications.",
      ],
    },
    {
      company: "SpicyFi GmbH",
      position: "React & Node.js Developer",
      location: "Switzerland",
      start_date: "2021-12-01",
      end_date: "2022-05-01",
      responsibilities: [
        "Built and maintained a full React Web3 game platform.",
        "Delivered high-performance SPAs with React and Redux.",
        "Developed RESTful APIs and backend integrations using Node.js.",
        "Implemented reusable front-end components and enhanced scalability.",
        "Collaborated with designers and backend teams to deliver UI/UX designs.",
        "Worked in Agile teams using Git for version control.",
      ],
    },
    {
      company: "Wealthface L.L.C.",
      position: "Mobile Apps and Web Developer",
      location: "Dubai, United Arab Emirates",
      start_date: "2020-04-01",
      end_date: "2021-12-01",
      responsibilities: [
        "Developed and maintained iOS & Android apps with React Native.",
        "Built responsive React web applications with scalable architecture.",
        "Integrated RESTful APIs and third-party services into apps.",
        "Implemented push notifications and real-time synchronization.",
        "Collaborated with designers and PMs in Agile teams to deliver projects.",
        "Led client training for CMS management and app usage.",
      ],
    },
  ],
  skills: [
    "React.js",
    "Next.js",
    "Node.js",
    "NestJS",
    "React Native",
    "PostgreSQL",
    "Supabase",
    "Web3",
    "RESTful APIs",
    "Redux",
    "Git",
    "Agile methodologies",
    "UI/UX design",
  ],
  languages: {
    Arabic: "Native",
    English: {
      Listening: "B2",
      Reading: "B2",
      Spoken_Production: "B1",
      Spoken_Interaction: "B2",
      Writing: "B2",
    },
  },
  soft_skills: [
    "Organizational skills",
    "Multitasking",
    "Mentoring",
    "Cross-functional collaboration",
    "Problem solving",
  ],
};
